[package]

name = "moses"

version = "0.1.0"

authors = ["schatzmeister <graf.schatzmeister@gmail.com>"]


build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.1"